version: '3.8'

services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile  
    container_name: car_service_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile 
    container_name: car_service_backend
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: car_service
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build:
      context: ./DB
      dockerfile: Dockerfile 
    container_name: car_service_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
